name: Build and Test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - name: Install server dependencies  
        working-directory: ./backend
        run: npm install
      - name: Server-side unit tests
        working-directory: ./backend
        run: npm run test
#      - name: Install client dependencies
#        working-directory: ./frontend/poll-app
#        run: npm install  